package opta.optawedding;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.entity.PlanningEntity
public class GuestAssignment implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Guest")
   private opta.optawedding.Guest guest;
   @org.kie.api.definition.type.Label(value = "Seat")
   @org.optaplanner.core.api.domain.variable.PlanningVariable(valueRangeProviderRefs = { "seatRange" })
   private opta.optawedding.Seat seat;

   public GuestAssignment()
   {
   }

   public opta.optawedding.Guest getGuest()
   {
      return this.guest;
   }

   public void setGuest(opta.optawedding.Guest guest)
   {
      this.guest = guest;
   }

   public opta.optawedding.Seat getSeat()
   {
      return this.seat;
   }

   public void setSeat(opta.optawedding.Seat seat)
   {
      this.seat = seat;
   }

   public GuestAssignment(opta.optawedding.Guest guest,
         opta.optawedding.Seat seat)
   {
      this.guest = guest;
      this.seat = seat;
   }

}