package opta.optawedding;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Seat implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Seat number")
   private int seatNumber;
   @org.kie.api.definition.type.Label(value = "Table")
   private opta.optawedding.Table table;

   public Seat()
   {
   }

   public int getSeatNumber()
   {
      return this.seatNumber;
   }

   public void setSeatNumber(int seatNumber)
   {
      this.seatNumber = seatNumber;
   }

   public opta.optawedding.Table getTable()
   {
      return this.table;
   }

   public void setTable(opta.optawedding.Table table)
   {
      this.table = table;
   }

   public Seat(int seatNumber, opta.optawedding.Table table)
   {
      this.seatNumber = seatNumber;
      this.table = table;
   }

}