package cb;

import org.optaplanner.core.impl.domain.solution.AbstractSolution;
import org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.solution.PlanningSolution
public class Schedule extends AbstractSolution<HardSoftScore> implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   public Schedule()
   {
   }

}