package cb;

import org.optaplanner.core.impl.domain.solution.AbstractSolution;
import org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.solution.PlanningSolution
public class Schedule extends AbstractSolution<HardSoftScore> implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<cb.Computer> computerList;
   private java.util.List<cb.Process> processList;

   public Schedule()
   {
   }

   public java.util.List<cb.Computer> getComputerList()
   {
      return this.computerList;
   }

   public void setComputerList(java.util.List<cb.Computer> computerList)
   {
      this.computerList = computerList;
   }

   public java.util.List<cb.Process> getProcessList()
   {
      return this.processList;
   }

   public void setProcessList(java.util.List<cb.Process> processList)
   {
      this.processList = processList;
   }

   public Schedule(java.util.List<cb.Computer> computerList,
         java.util.List<cb.Process> processList)
   {
      this.computerList = computerList;
      this.processList = processList;
   }

}