package opta.curriculumcourse;

import org.optaplanner.core.impl.domain.solution.AbstractSolution;
import org.optaplanner.core.api.score.buildin.bendable.BendableScore;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Day implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int dayIndex;
	private java.util.List<Period> periodList;

	private java.lang.Long id;

	public Day() {
	}

	public int getDayIndex() {
		return this.dayIndex;
	}

	public void setDayIndex(int dayIndex) {
		this.dayIndex = dayIndex;
	}

	public java.util.List<Period> getPeriodList() {
		return this.periodList;
	}

	public void setPeriodList(
			java.util.List<Period> periodList) {
		this.periodList = periodList;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public Day(int dayIndex,
			java.util.List<Period> periodList,
			java.lang.Long id) {
		this.dayIndex = dayIndex;
		this.periodList = periodList;
		this.id = id;
	}

}