package opta.curriculumcourse;

import org.optaplanner.core.impl.domain.solution.AbstractSolution;
import org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Period implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Day day;
	private Timeslot timeslot;

	private java.lang.Long id;

	public Period() {
	}

	public Day getDay() {
		return this.day;
	}

	public void setDay(Day day) {
		this.day = day;
	}

	public Timeslot getTimeslot() {
		return this.timeslot;
	}

	public void setTimeslot(Timeslot timeslot) {
		this.timeslot = timeslot;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public Period( Day day,
                   Timeslot timeslot, java.lang.Long id) {
		this.day = day;
		this.timeslot = timeslot;
		this.id = id;
	}

}