package opta.curriculumcourse;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Timeslot implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int timeslotIndex;

	private java.lang.Long id;

	public Timeslot() {
	}

	public int getTimeslotIndex() {
		return this.timeslotIndex;
	}

	public void setTimeslotIndex(int timeslotIndex) {
		this.timeslotIndex = timeslotIndex;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public Timeslot(int timeslotIndex, java.lang.Long id) {
		this.timeslotIndex = timeslotIndex;
		this.id = id;
	}

}